### ISSUE TITLE
Map doesn't switch to when you travel to different worlds

### ISSUE THREAD

**Issue by emielderckx** [jpenilla/squaremap-client#6]
When you die in the `overworld`, `nether` or `the end`, and you respawn in another world, the map will not update.
Also, when traveling through the end exit the map doesn't switch worlds.

**Comment by jpenilla** [comment]
Should be fixed by https://github.com/jpenilla/squaremap/commit/a1e81fa5acdc8adfded930b5e27593cd38c06bf0
